# Generated by Django 3.1.4 on 2020-12-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('type', 'variety')},
        ),
    ]
