# Generated by Django 3.1.4 on 2020-12-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewadjunctbatch',
            options={'verbose_name': 'Fermentation agent/Dry hopping'},
        ),
        migrations.RenameField(
            model_name='brewfermentationanalysis',
            old_name='plateau_degree_or_density',
            new_name='plato_degree_or_density',
        ),
        migrations.AddField(
            model_name='brewadjunctbatch',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewboilingingredientbatch',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewmashingingredientbatch',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewwhirlpoolingredientbatch',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewyeastbatch',
            name='yeast',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
            preserve_default=False,
        ),
    ]
