# Generated by Django 3.1.4 on 2020-12-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0002_auto_20201220_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewadjunctbatch',
            options={'verbose_name': 'Fermentation agents/Dry hopping'},
        ),
        migrations.AlterModelOptions(
            name='brewfermentationanalysis',
            options={'verbose_name_plural': 'Fermentation analysis'},
        ),
        migrations.AlterModelOptions(
            name='brewfermentationstep',
            options={'verbose_name_plural': 'Fermentation steps'},
        ),
    ]
