# Generated by Django 3.1.4 on 2020-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0002_auto_20201218_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producer',
            new_name='Supplier',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit',
            field=models.CharField(default='kg', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
