# Generated by Django 3.1.4 on 2020-12-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0002_auto_20201220_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='capacity',
            field=models.IntegerField(default=2000, help_text='Capacity in liters'),
            preserve_default=False,
        ),
    ]
