# Generated by Django 3.1.4 on 2020-12-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0002_auto_20201220_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='name',
            field=models.CharField(help_text='Name/number of the tank', max_length=50, unique=True),
        ),
    ]
