# Generated by Django 3.1.4 on 2020-12-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0003_auto_20201220_1250'),
        ('brewbrew', '0003_tank_capacity'),
    ]

    operations = [
    ]
