# Generated by Django 3.1.4 on 2020-12-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0003_auto_20201220_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='fermentation_tank',
            field=models.ForeignKey(blank=True, help_text='Tank in which to ferment', null=True, on_delete=django.db.models.deletion.PROTECT, to='brewbrew.tank'),
        ),
    ]
