# Generated by Django 3.1.4 on 2020-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0004_auto_20201219_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='boiling_duration',
            field=models.IntegerField(help_text='Duration of boiling step in minutes'),
        ),
    ]
