# Generated by Django 3.1.4 on 2020-12-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0004_auto_20201220_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewadjunctbatch',
            name='ingredient_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredientbatch'),
        ),
        migrations.AlterField(
            model_name='brewboilingingredientbatch',
            name='ingredient_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredientbatch'),
        ),
        migrations.AlterField(
            model_name='brewwhirlpoolingredientbatch',
            name='ingredient_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredientbatch'),
        ),
        migrations.AlterField(
            model_name='brewyeastbatch',
            name='yeast_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredientbatch'),
        ),
    ]
