# Generated by Django 3.1.4 on 2020-12-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0005_auto_20201219_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeYeasts',
            new_name='RecipeYeast',
        ),
    ]
