# Generated by Django 3.1.4 on 2020-12-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0005_auto_20201220_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientbatch',
            name='ingredient',
            field=models.ForeignKey(help_text='Ingredient', on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientbatch',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier', on_delete=django.db.models.deletion.PROTECT, to='brewbrew.supplier'),
        ),
        migrations.AlterField(
            model_name='recipeadjunct',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeboilingingredient',
            name='boiling_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipemashingingredient',
            name='mashing_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipewhirlpoolingredient',
            name='whirlpool_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeyeast',
            name='yeast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredient'),
        ),
    ]
