# Generated by Django 3.1.4 on 2020-12-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0006_auto_20201219_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrewingStep',
            new_name='RecipeBrewingStep',
        ),
        migrations.RenameModel(
            old_name='FermentationStep',
            new_name='RecipeFermentationStep',
        ),
    ]
