# Generated by Django 3.1.4 on 2020-12-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0006_auto_20201220_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewboilingingredientbatch',
            name='time',
            field=models.IntegerField(blank=True, help_text='When the ingredient was added (in minutes from the end of boiling)', null=True),
        ),
    ]
