# Generated by Django 3.1.4 on 2020-12-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0007_auto_20201220_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewboilingingredientbatch',
            options={'verbose_name_plural': 'Boiling ingredients'},
        ),
        migrations.AlterModelOptions(
            name='brewbrewingstep',
            options={'verbose_name': 'Brewing step', 'verbose_name_plural': 'Brewing steps'},
        ),
        migrations.AlterModelOptions(
            name='brewmashingingredientbatch',
            options={'verbose_name': 'Mashing ingredient', 'verbose_name_plural': 'Mashing ingredients'},
        ),
        migrations.AlterModelOptions(
            name='brewwhirlpoolingredientbatch',
            options={'verbose_name_plural': 'Whirlpool ingredients'},
        ),
        migrations.AlterModelOptions(
            name='brewyeastbatch',
            options={'verbose_name_plural': 'Yeasts'},
        ),
        migrations.RemoveField(
            model_name='brew',
            name='adjuncts_start_time',
        ),
    ]
