# Generated by Django 3.1.4 on 2020-12-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0008_auto_20201222_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeadjunct',
            options={'verbose_name': 'Adjunct', 'verbose_name_plural': 'Adjuncts'},
        ),
        migrations.AlterModelOptions(
            name='recipeboilingingredient',
            options={'verbose_name': 'Boiling ingredient', 'verbose_name_plural': 'Boiling ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipebrewingstep',
            options={'verbose_name': 'Brewing step', 'verbose_name_plural': 'Brewing steps'},
        ),
        migrations.AlterModelOptions(
            name='recipefermentationstep',
            options={'verbose_name': 'Fermentation step', 'verbose_name_plural': 'Fermentation steps'},
        ),
        migrations.AlterModelOptions(
            name='recipemashingingredient',
            options={'verbose_name': 'Mashing ingredient', 'verbose_name_plural': 'Mashing ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipewhirlpoolingredient',
            options={'verbose_name': 'Whirlpool ingredient', 'verbose_name_plural': 'Whirlpool ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipeyeast',
            options={'verbose_name': 'Yeast', 'verbose_name_plural': 'Yeasts'},
        ),
    ]
