# Generated by Django 3.1.4 on 2020-12-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0008_auto_20201219_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipefermentationstep',
            name='name',
            field=models.CharField(default='', help_text='Name of the fermentation step', max_length=50),
            preserve_default=False,
        ),
    ]
