# Generated by Django 3.1.4 on 2020-12-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0008_auto_20201220_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeadjunct',
            name='day',
            field=models.IntegerField(default=0, help_text='Day to add the adjunct/hop (from the start of fermentation)'),
            preserve_default=False,
        ),
    ]
