# Generated by Django 3.1.4 on 2020-12-20 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0009_recipeadjunct_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewadjunctbatch',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 15, 22, 47, 517876), help_text='Date when the adjunct/hop was added'),
            preserve_default=False,
        ),
    ]
