# Generated by Django 3.1.4 on 2020-12-20 10:29

import brewbrew.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0009_recipefermentationstep_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[(brewbrew.models.IngredientType['GRAIN'], 'Grain'), (brewbrew.models.IngredientType['HOP'], 'Hop'), (brewbrew.models.IngredientType['YEAST'], 'Yeast'), (brewbrew.models.IngredientType['ADJUNCT'], 'Adjunct'), (brewbrew.models.IngredientType['FRUIT'], 'Fruit')], default='Grain', help_text='The type of ingredient', max_length=50),
            preserve_default=False,
        ),
    ]
