# Generated by Django 3.1.4 on 2020-12-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0009_auto_20201222_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['variety', 'supplier__name']},
        ),
        migrations.AlterModelOptions(
            name='ingredientbatch',
            options={'ordering': ['ingredient__variety', 'ingredient__supplier', '-batch_number']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
    ]
