# Generated by Django 3.1.4 on 2020-12-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0010_ingredient_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe',
        ),
    ]
