# Generated by Django 3.1.4 on 2020-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0010_brewadjunctbatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity of beer obtained with this brew', null=True),
        ),
    ]
