# Generated by Django 3.1.4 on 2020-12-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0010_auto_20201222_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientbatch',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='ingredientbatch',
            name='quantity',
        ),
        migrations.CreateModel(
            name='IngredientBatchInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(help_text='Bill number', max_length=50)),
                ('quantity', models.FloatField(help_text='Quantity ')),
                ('ingredient_batch', models.ForeignKey(help_text='The batch that this entry refers to', on_delete=django.db.models.deletion.PROTECT, to='brewbrew.ingredientbatch')),
            ],
        ),
    ]
