# Generated by Django 3.1.4 on 2020-12-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0011_remove_recipe_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeadjunct',
            old_name='yeast',
            new_name='ingredient',
        ),
    ]
