# Generated by Django 3.1.4 on 2020-12-22 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0011_auto_20201222_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientbatchinput',
            name='input_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
