# Generated by Django 3.1.4 on 2020-12-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0012_auto_20201220_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('GRAIN', 'Grain'), ('HOP', 'Hop'), ('YEAST', 'Yeast'), ('ADJUNCT', 'Adjunct'), ('FRUIT', 'Fruit')], help_text='The type of ingredient', max_length=50),
        ),
    ]
