# Generated by Django 3.1.4 on 2020-12-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0012_auto_20201220_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientbatch',
            old_name='producer',
            new_name='supplier',
        ),
    ]
