# Generated by Django 3.1.4 on 2020-12-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewbrew', '0013_auto_20201220_1209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('type', 'variety')},
        ),
    ]
